apiVersion: v1
kind: Node
metadata:
  name: guru-reworker1
  labels:
    app: web-app
    order: order-app
    sign: sign-app
---
apiVersion: v1
kind: Node
metadata:
  name: guru-reworker2
  labels:
    app: was-app
